[project]
name = "expenses-ingestion"
version = "0.1.0"
requires-python = ">=3.9"
dependencies = [
    "streamlit==1.43.1",
    "sqlalchemy==2.0.40",
    "prefect>=3.4.5",
    "psycopg2-binary>=2.9.10",
]

[dependency-groups]
dev = [
    "ruff>=0.11.2",
]
