"""add account_type column

Revision ID: 023866e825ab
Revises: 2034c9597329
Create Date: 2025-04-11 15:51:58.766152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '023866e825ab'
down_revision: Union[str, None] = '2034c9597329'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cfg_t_files', sa.Column('account_type', sa.String(length=3), nullable=False), schema='config_sch')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cfg_t_files', 'account_type', schema='config_sch')
    # ### end Alembic commands ###
