"""Initial schema

Revision ID: 2034c9597329
Revises: 
Create Date: 2025-04-11 15:48:01.187709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2034c9597329'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cfg_t_file_config',
    sa.Column('config_id', sa.Integer(), nullable=False),
    sa.Column('file_pattern', sa.String(), nullable=False),
    sa.Column('date_format', sa.String(), nullable=False),
    sa.Column('amount_sign', sa.Integer(), nullable=False),
    sa.Column('delimiter', sa.String(), nullable=False),
    sa.Column('decimal_separator', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('config_id'),
    schema='config_sch'
    )
    op.create_table('cfg_t_file_status',
    sa.Column('file_status_id', sa.Integer(), nullable=False),
    sa.Column('file_status_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('file_status_id'),
    sa.UniqueConstraint('file_status_name'),
    schema='config_sch'
    )
    op.create_table('cfg_t_files',
    sa.Column('file_id', sa.String(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('number_rows', sa.Integer(), nullable=False),
    sa.Column('checksum', sa.String(length=255), nullable=False),
    sa.Column('file_status_id', sa.Integer(), nullable=False),
    sa.Column('file_config_id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('inserted_datetime', sa.DateTime(), nullable=False),
    sa.Column('ingested_datetime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['file_config_id'], ['config_sch.cfg_t_file_config.config_id'], ),
    sa.ForeignKeyConstraint(['file_status_id'], ['config_sch.cfg_t_file_status.file_status_id'], ),
    sa.PrimaryKeyConstraint('file_id'),
    sa.UniqueConstraint('checksum'),
    schema='config_sch'
    )
    op.create_table('s_t_expenses',
    sa.Column('file_id', sa.String(), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['config_sch.cfg_t_files.file_id'], ),
    sa.PrimaryKeyConstraint('file_id', 'transaction_date'),
    schema='s_sch'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('s_t_expenses', schema='s_sch')
    op.drop_table('cfg_t_files', schema='config_sch')
    op.drop_table('cfg_t_file_status', schema='config_sch')
    op.drop_table('cfg_t_file_config', schema='config_sch')
    # ### end Alembic commands ###
