"""add new model for failed expenses

Revision ID: 576341b0b963
Revises: 915241ea7941
Create Date: 2025-04-12 19:17:26.579482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '576341b0b963'
down_revision: Union[str, None] = '915241ea7941'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('s_t_expenses_failed',
    sa.Column('failed_expense_id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.String(), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['config_sch.cfg_t_files.file_id'], ),
    sa.PrimaryKeyConstraint('failed_expense_id'),
    schema='s_sch'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('s_t_expenses_failed', schema='s_sch')
    # ### end Alembic commands ###
