"""add expected_schema column to file config

Revision ID: 5b6c01cd5a71
Revises: b5fc1541dc6d
Create Date: 2025-04-16 10:29:09.676509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5b6c01cd5a71'
down_revision: Union[str, None] = 'b5fc1541dc6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cfg_t_file_config', 'expected_schema',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.String(),
               existing_nullable=True,
               schema='config_sch')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cfg_t_file_config', 'expected_schema',
               existing_type=sa.String(),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True,
               schema='config_sch')
    # ### end Alembic commands ###
