"""update col settings

Revision ID: 75ee24bcd3de
Revises: be9575bdbe6f
Create Date: 2025-04-11 16:04:57.156519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '75ee24bcd3de'
down_revision: Union[str, None] = 'be9575bdbe6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cfg_t_files', 'file_status_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               schema='config_sch')
    op.alter_column('cfg_t_files', 'inserted_datetime',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               schema='config_sch')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cfg_t_files', 'inserted_datetime',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               schema='config_sch')
    op.alter_column('cfg_t_files', 'file_status_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               schema='config_sch')
    # ### end Alembic commands ###
