"""auto increment

Revision ID: 7f517f251fcf
Revises: 576341b0b963
Create Date: 2025-04-12 19:21:34.814711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f517f251fcf'
down_revision: Union[str, None] = '576341b0b963'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('s_t_expenses_failed', 'transaction_date',
               existing_type=sa.DATE(),
               type_=sa.String(),
               existing_nullable=True,
               schema='s_sch')
    op.alter_column('s_t_expenses_failed', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.String(),
               existing_nullable=True,
               schema='s_sch')
    op.alter_column('s_t_expenses_failed', 'error_message',
               existing_type=sa.VARCHAR(),
               nullable=True,
               schema='s_sch')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('s_t_expenses_failed', 'error_message',
               existing_type=sa.VARCHAR(),
               nullable=False,
               schema='s_sch')
    op.alter_column('s_t_expenses_failed', 'amount',
               existing_type=sa.String(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True,
               schema='s_sch')
    op.alter_column('s_t_expenses_failed', 'transaction_date',
               existing_type=sa.String(),
               type_=sa.DATE(),
               existing_nullable=True,
               schema='s_sch')
    # ### end Alembic commands ###
