"""add account col to expenses

Revision ID: a077cb3b5855
Revises: eaead55b2d19
Create Date: 2025-04-15 15:29:06.651275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a077cb3b5855'
down_revision: Union[str, None] = 'eaead55b2d19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('s_t_expenses', sa.Column('account', sa.String(length=255), nullable=True), schema='s_sch')
    op.drop_constraint('s_t_expenses_file_id_fkey', 's_t_expenses', schema='s_sch', type_='foreignkey')
    op.create_foreign_key(None, 's_t_expenses', 'cfg_t_files', ['file_id'], ['file_id'], source_schema='s_sch', referent_schema='config_sch')
    op.add_column('s_t_expenses_failed', sa.Column('account', sa.String(), nullable=True), schema='s_sch')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('s_t_expenses_failed', 'account', schema='s_sch')
    op.drop_constraint(None, 's_t_expenses', schema='s_sch', type_='foreignkey')
    op.create_foreign_key('s_t_expenses_file_id_fkey', 's_t_expenses', 'cfg_t_files', ['file_id'], ['file_id'], source_schema='s_sch', referent_schema='config_sch', ondelete='CASCADE')
    op.drop_column('s_t_expenses', 'account', schema='s_sch')
    # ### end Alembic commands ###
