"""add expected_schema column to file config

Revision ID: b5fc1541dc6d
Revises: a077cb3b5855
Create Date: 2025-04-16 10:26:58.610025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5fc1541dc6d'
down_revision: Union[str, None] = 'a077cb3b5855'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cfg_t_file_config', sa.Column('expected_schema', sa.JSON(), nullable=True), schema='config_sch')
    op.drop_constraint('s_t_expenses_file_id_fkey', 's_t_expenses', schema='s_sch', type_='foreignkey')
    op.create_foreign_key(None, 's_t_expenses', 'cfg_t_files', ['file_id'], ['file_id'], source_schema='s_sch', referent_schema='config_sch')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 's_t_expenses', schema='s_sch', type_='foreignkey')
    op.create_foreign_key('s_t_expenses_file_id_fkey', 's_t_expenses', 'cfg_t_files', ['file_id'], ['file_id'], source_schema='s_sch', referent_schema='config_sch', ondelete='CASCADE')
    op.drop_column('cfg_t_file_config', 'expected_schema', schema='config_sch')
    # ### end Alembic commands ###
