"""add category column to expenses

Revision ID: d760f8cdf5ab
Revises: 06c81ad68717
Create Date: 2025-04-17 15:40:48.042785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd760f8cdf5ab'
down_revision: Union[str, None] = '06c81ad68717'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('g_t_category_expense_summary', 'total_expenses',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=12, asdecimal=2),
               existing_nullable=False,
               schema='g_sch')
    op.alter_column('g_t_monthly_summary', 'total_expenses',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=12, asdecimal=2),
               existing_nullable=False,
               schema='g_sch')
    op.alter_column('g_t_monthly_summary', 'total_earnings',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=12, asdecimal=2),
               existing_nullable=False,
               schema='g_sch')
    op.alter_column('g_t_monthly_summary', 'total_savings',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=12, asdecimal=2),
               existing_nullable=False,
               schema='g_sch')
    op.alter_column('g_t_monthly_summary', 'prev_month_expenses',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=12, asdecimal=2),
               existing_nullable=False,
               schema='g_sch')
    op.alter_column('g_t_monthly_summary', 'prev_month_earnings',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=12, asdecimal=2),
               existing_nullable=False,
               schema='g_sch')
    op.alter_column('g_t_monthly_summary', 'prev_month_savings',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=12, asdecimal=2),
               existing_nullable=False,
               schema='g_sch')
    op.alter_column('g_t_savings_rate_summary', 'savings_rate',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=5, asdecimal=4),
               existing_nullable=False,
               schema='g_sch')
    op.add_column('s_t_expenses', sa.Column('category', sa.String(), nullable=True), schema='s_sch')
    op.add_column('s_t_expenses_failed', sa.Column('category', sa.String(), nullable=True), schema='s_sch')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('s_t_expenses_failed', 'category', schema='s_sch')
    op.drop_column('s_t_expenses', 'category', schema='s_sch')
    op.alter_column('g_t_savings_rate_summary', 'savings_rate',
               existing_type=sa.Float(precision=5, asdecimal=4),
               type_=sa.REAL(),
               existing_nullable=False,
               schema='g_sch')
    op.alter_column('g_t_monthly_summary', 'prev_month_savings',
               existing_type=sa.Float(precision=12, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=False,
               schema='g_sch')
    op.alter_column('g_t_monthly_summary', 'prev_month_earnings',
               existing_type=sa.Float(precision=12, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=False,
               schema='g_sch')
    op.alter_column('g_t_monthly_summary', 'prev_month_expenses',
               existing_type=sa.Float(precision=12, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=False,
               schema='g_sch')
    op.alter_column('g_t_monthly_summary', 'total_savings',
               existing_type=sa.Float(precision=12, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=False,
               schema='g_sch')
    op.alter_column('g_t_monthly_summary', 'total_earnings',
               existing_type=sa.Float(precision=12, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=False,
               schema='g_sch')
    op.alter_column('g_t_monthly_summary', 'total_expenses',
               existing_type=sa.Float(precision=12, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=False,
               schema='g_sch')
    op.alter_column('g_t_category_expense_summary', 'total_expenses',
               existing_type=sa.Float(precision=12, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=False,
               schema='g_sch')
    # ### end Alembic commands ###
