"""update col settings

Revision ID: dd1e2a8aab46
Revises: 023866e825ab
Create Date: 2025-04-11 15:57:43.535515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd1e2a8aab46'
down_revision: Union[str, None] = '023866e825ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cfg_t_files', 'file_config_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               schema='config_sch')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cfg_t_files', 'file_config_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               schema='config_sch')
    # ### end Alembic commands ###
