"""add class_name

Revision ID: e2c3ff6316d7
Revises: 5d7b2cdbb0a7
Create Date: 2025-04-19 17:10:31.920264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2c3ff6316d7'
down_revision: Union[str, None] = '5d7b2cdbb0a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('g_t_category_expense_summary', 'total_expenses',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=12, asdecimal=2),
               existing_nullable=False,
               schema='g_sch')
    op.alter_column('g_t_monthly_summary', 'total_expenses',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=12, asdecimal=2),
               existing_nullable=False,
               schema='g_sch')
    op.alter_column('g_t_monthly_summary', 'total_earnings',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=12, asdecimal=2),
               existing_nullable=False,
               schema='g_sch')
    op.alter_column('g_t_monthly_summary', 'total_savings',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=12, asdecimal=2),
               existing_nullable=False,
               schema='g_sch')
    op.alter_column('g_t_savings_rate_summary', 'savings_rate',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=5, asdecimal=4),
               existing_nullable=False,
               schema='g_sch')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('g_t_savings_rate_summary', 'savings_rate',
               existing_type=sa.Float(precision=5, asdecimal=4),
               type_=sa.REAL(),
               existing_nullable=False,
               schema='g_sch')
    op.alter_column('g_t_monthly_summary', 'total_savings',
               existing_type=sa.Float(precision=12, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=False,
               schema='g_sch')
    op.alter_column('g_t_monthly_summary', 'total_earnings',
               existing_type=sa.Float(precision=12, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=False,
               schema='g_sch')
    op.alter_column('g_t_monthly_summary', 'total_expenses',
               existing_type=sa.Float(precision=12, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=False,
               schema='g_sch')
    op.alter_column('g_t_category_expense_summary', 'total_expenses',
               existing_type=sa.Float(precision=12, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=False,
               schema='g_sch')
    # ### end Alembic commands ###
