"""test

Revision ID: e46d82b9f5a6
Revises: 07cc3fe2b325
Create Date: 2025-04-17 15:32:26.019494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e46d82b9f5a6'
down_revision: Union[str, None] = '07cc3fe2b325'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('g_t_category_expense_summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_month', sa.Date(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('total_expenses', sa.Float(precision=12, asdecimal=2), nullable=False),
    sa.Column('inserted_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='g_sch'
    )
    op.create_table('g_t_monthly_summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_month', sa.Date(), nullable=False),
    sa.Column('total_expenses', sa.Float(precision=12, asdecimal=2), nullable=False),
    sa.Column('total_earnings', sa.Float(precision=12, asdecimal=2), nullable=False),
    sa.Column('total_savings', sa.Float(precision=12, asdecimal=2), nullable=False),
    sa.Column('prev_month_expenses', sa.Float(precision=12, asdecimal=2), nullable=False),
    sa.Column('prev_month_earnings', sa.Float(precision=12, asdecimal=2), nullable=False),
    sa.Column('prev_month_savings', sa.Float(precision=12, asdecimal=2), nullable=False),
    sa.Column('dummy', sa.String(), nullable=True),
    sa.Column('inserted_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='g_sch'
    )
    op.create_table('g_t_pipeline_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('g_table_name', sa.String(), nullable=False),
    sa.Column('module_path', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('run_frequency', sa.String(), nullable=True),
    sa.Column('last_run', sa.DateTime(), nullable=True),
    sa.Column('inserted_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('g_table_name'),
    schema='g_sch'
    )
    op.create_table('g_t_savings_rate_summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_month', sa.Date(), nullable=False),
    sa.Column('savings_rate', sa.Float(precision=5, asdecimal=4), nullable=False),
    sa.Column('inserted_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='g_sch'
    )
    op.drop_table('g_t_expenses', schema='g_sch')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('g_t_expenses',
    sa.Column('expense_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('file_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('transaction_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('account', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('category', sa.TEXT(), autoincrement=False, nullable=True),
    schema='g_sch'
    )
    op.drop_table('g_t_savings_rate_summary', schema='g_sch')
    op.drop_table('g_t_pipeline_config', schema='g_sch')
    op.drop_table('g_t_monthly_summary', schema='g_sch')
    op.drop_table('g_t_category_expense_summary', schema='g_sch')
    # ### end Alembic commands ###
