"""add encoding to file config

Revision ID: eaead55b2d19
Revises: 736296d8c235
Create Date: 2025-04-15 13:38:04.380768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eaead55b2d19'
down_revision: Union[str, None] = '736296d8c235'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cfg_t_file_config', sa.Column('encoding', sa.String(), nullable=True), schema='config_sch')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cfg_t_file_config', 'encoding', schema='config_sch')
    # ### end Alembic commands ###
