name: Ping Database
description: A GitHub Action to ping a Supabase database to keep it active.

on:
  schedule:
    - cron: "0 9 * * 0"  # Runs at 9:00 AM UTC every Sunday
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Supabase REST API
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: |
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" \
            -H "apikey: $SUPABASE_KEY" \
            -H "Authorization: Bearer $SUPABASE_KEY" \
            "$SUPABASE_URL/rest/v1/")
          
          echo "HTTP status: $STATUS"
          
          if [ "$STATUS" -ne 200 ]; then
            echo "❌ Ping failed with status $STATUS"
            exit 1
          else
            echo "✅ Ping successful"
          fi